### PR TITLE
Replace SBR Affects Unit Production For Damage From Bombing Done To U…

### PR DESCRIPTION
**Pull request by simon33-2**
…nits Instead Of Territories

One of the last two steps to resolve #1330 from TripleA.

### CODE REVIEW

**Comment by FrostionAAA** [comment]
I don’t understand. I can see what you want to change withing the XML, but what would this change do? Is there a problem with the current XML? Does it fix errors from occurring within Iron War?
PS: This is the first PR I have seen in regards to a map of mine, so I don’t know how to handle it :-/

**Comment by DanVanAtta** [comment]
Fair questions @FrostionAAA 

AFAIK we are fixing a long running bug that was introduced in 1.9 where SBRs were not being properly handled (damage was being taken off of country PU  rather than being damage being assigned to the factory).

If this actually introduces a problem, we can undo this update by hitting the 'revert' button.

**Comment by FrostionAAA** [comment]
The map seems to work fine with these XML changes in place. But, I don’t understand: What should "SBR Affects Unit Production" then do, if it is not needed to be "true" to lower a factory's production papacity when damaged?

Also, if "SBR Affects Unit Production" = true is unnecessary for lowering production papacity, how can a mapmaker make a factory that DOES NOT lower its production when damaged?

**Comment by DanVanAtta** [comment]
There is a lot of context in this very long thread:
https://github.com/triplea-game/triplea/issues/1330
https://github.com/triplea-game/triplea/issues/1330#issuecomment-264685228
https://github.com/triplea-game/triplea/issues/1330#issuecomment-265089242
https://github.com/triplea-game/triplea/issues/1330#issuecomment-278213214

Essentially the property would be redundant already with an existing. I'd have @simon33-2 jump in to explain more if that does not clarify further.

**Comment by simon33-2** [comment]
"SBR Affects Unit Production" is a redundant property that is being removed to save confusion. It doesn't do anything.

**Comment by simon33-2** [comment]
> Also, if "SBR Affects Unit Production" = true is unnecessary for lowering production papacity, how can a mapmaker make a factory that DOES NOT lower its production when damaged?

You should use "Damage From Bombing Done To Units Instead Of Territories".
true = factories damaged
false = IPCs reduced

**Pull request merged**
